/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//que pedo morro
//Holi ppro
package Abarrotes;
//no mms skd
import Base_Datos.Conexion;
import Clases.Validaciones;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Emir
 */
public class Agregar extends javax.swing.JFrame {
    Conexion con = new Conexion();
    PreparedStatement st = null;
    ResultSet rs , idAconse = null, kk = null;
    Validaciones ex = new Validaciones();
    /**
     * Creates new form Agregar
     */
    public Agregar() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtf_nom = new javax.swing.JTextField();
        jlbl_n = new javax.swing.JLabel();
        jlbl_precio = new javax.swing.JLabel();
        jtf_precio = new javax.swing.JTextField();
        hlbl_cant = new javax.swing.JLabel();
        jCB_tipo = new javax.swing.JComboBox<>();
        jlbl_tipo = new javax.swing.JLabel();
        jbtn_cancelar = new javax.swing.JButton();
        jbtn_guardar = new javax.swing.JButton();
        jtf_Cantidad1 = new javax.swing.JTextField();
        txt_actual = new javax.swing.JLabel();
        jtf_actualCantidad = new javax.swing.JTextField();
        jlb_precioCompra = new javax.swing.JLabel();
        jtf_precio1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 188, 212));

        jtf_nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_nomKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_nomKeyTyped(evt);
            }
        });

        jlbl_n.setText("Nombre:");

        jlbl_precio.setText("Precio Venta:");

        jtf_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_precioActionPerformed(evt);
            }
        });
        jtf_precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_precioKeyTyped(evt);
            }
        });

        hlbl_cant.setText("Cantidad minima en stock:");

        jCB_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cereal", "Alcohol" }));
        jCB_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_tipoActionPerformed(evt);
            }
        });

        jlbl_tipo.setText("Categoria:");

        jbtn_cancelar.setBackground(new java.awt.Color(0, 150, 136));
        jbtn_cancelar.setText("Cancelar");
        jbtn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cancelarActionPerformed(evt);
            }
        });

        jbtn_guardar.setBackground(new java.awt.Color(0, 150, 136));
        jbtn_guardar.setText("Guardar");
        jbtn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_guardarActionPerformed(evt);
            }
        });

        jtf_Cantidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_Cantidad1ActionPerformed(evt);
            }
        });
        jtf_Cantidad1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_Cantidad1KeyTyped(evt);
            }
        });

        txt_actual.setText("Cantidad Actual:");

        jtf_actualCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_actualCantidadActionPerformed(evt);
            }
        });
        jtf_actualCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_actualCantidadKeyTyped(evt);
            }
        });

        jlb_precioCompra.setText("Precio Compra:");

        jtf_precio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_precio1ActionPerformed(evt);
            }
        });
        jtf_precio1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_precio1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(hlbl_cant)
                                .addComponent(jCB_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_cancelar))
                        .addComponent(jtf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlbl_n)
                        .addComponent(txt_actual)
                        .addComponent(jtf_actualCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlbl_precio))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jbtn_guardar))
                        .addComponent(jtf_Cantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlb_precioCompra)
                    .addComponent(jtf_precio1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_tipo))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jlbl_n)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbl_precio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jbtn_guardar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jbtn_cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlb_precioCompra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_precio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbl_tipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCB_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hlbl_cant)
                        .addGap(4, 4, 4)))
                .addComponent(jtf_Cantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_actual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_actualCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cancelarActionPerformed
        this.setVisible(false);
        Almacen a= new Almacen();
        a.setVisible(true);
        
    }//GEN-LAST:event_jbtn_cancelarActionPerformed

    private void jtf_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_precioActionPerformed

    private void jbtn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_guardarActionPerformed
        
         try{
             int guardar;
             st=con.obtenerConexion().prepareStatement
             ("INSERT INTO Articulo(idArticulo,nombre,precioVenta,precioCompra,categoria,StockMini,Stock,eliminar)values("+null+",'"+jtf_nom.getText()+"','"+jtf_precio.getText()+"','"+jtf_precio1.getText()+"','"+jCB_tipo.getSelectedItem().toString()+"','"+jtf_Cantidad1.getText()+"','"+jtf_actualCantidad.getText()+"',1);");
             guardar = st.executeUpdate();
              if (guardar > 0)
                    {
                       System.out.println(" SE INSERTO producto");
                       JOptionPane.showMessageDialog(null,"Insersión Correcta");
                       limpiar_campos();
                       this.setVisible(false);
                       Almacen b = new Almacen();
                       b.setVisible(true);
                      }   
              else
                    {
                        
                       System.out.println("NO SE INSERTO EL articulo");
                       
                     }
         }catch(Exception e){
             
         }
    }//GEN-LAST:event_jbtn_guardarActionPerformed

    public void limpiar_campos(){
        jtf_nom.setText("");
        jtf_precio.setText("");
        jtf_Cantidad1.setText("");
        jtf_actualCantidad.setText("");
    }
    private void jtf_Cantidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_Cantidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_Cantidad1ActionPerformed

    private void jtf_actualCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_actualCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_actualCantidadActionPerformed

    private void jCB_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCB_tipoActionPerformed

    private void jtf_nomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_nomKeyPressed
        
        
    }//GEN-LAST:event_jtf_nomKeyPressed

    private void jtf_nomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_nomKeyTyped
      
        ex.validarCar(evt, jtf_nom);
    }//GEN-LAST:event_jtf_nomKeyTyped

    private void jtf_precioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_precioKeyTyped
        ex.validar_num(evt,jtf_precio);
    }//GEN-LAST:event_jtf_precioKeyTyped

    private void jtf_Cantidad1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_Cantidad1KeyTyped
        ex.validar_num(evt,jtf_Cantidad1);
    }//GEN-LAST:event_jtf_Cantidad1KeyTyped

    private void jtf_actualCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_actualCantidadKeyTyped
        ex.validar_num(evt,jtf_actualCantidad);
    }//GEN-LAST:event_jtf_actualCantidadKeyTyped

    private void jtf_precio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_precio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_precio1ActionPerformed

    private void jtf_precio1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_precio1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_precio1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hlbl_cant;
    private javax.swing.JComboBox<String> jCB_tipo;
    private javax.swing.JButton jbtn_cancelar;
    private javax.swing.JButton jbtn_guardar;
    private javax.swing.JLabel jlb_precioCompra;
    private javax.swing.JLabel jlbl_n;
    private javax.swing.JLabel jlbl_precio;
    private javax.swing.JLabel jlbl_tipo;
    private javax.swing.JTextField jtf_Cantidad1;
    private javax.swing.JTextField jtf_actualCantidad;
    private javax.swing.JTextField jtf_nom;
    private javax.swing.JTextField jtf_precio;
    private javax.swing.JTextField jtf_precio1;
    private javax.swing.JLabel txt_actual;
    // End of variables declaration//GEN-END:variables
}
