/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Abarrotes;

import Base_Datos.Conexion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emir
 */
public class Almacen extends javax.swing.JFrame {
    Conexion con = new Conexion();
    PreparedStatement p=null;
    ResultSet res, idPConsec=null, kk=null;
    int idP_=0;
    String queryGuardar="";
    /**
     * Creates new form Almacen
     */
    public Almacen() {
        initComponents();
        articulos();
    }
    
    public void articulos(){
       DefaultTableModel articulos = new DefaultTableModel();
        ResultSet rs = con.getTable("select * from Articulo where eliminar = 1");
        articulos.setColumnIdentifiers(new Object[]{"ID","Nombre","PrecioCompra","PrecioVenta","Categoria","Stock Minimo","Stock Actual"});
        try {
            while(rs.next()){
                articulos.addRow(new Object[]{rs.getString("idArticulo"),rs.getString("nombre"),rs.getString("precioCompra"),rs.getString("precioVenta"),rs.getString("categoria"),rs.getString("StockMini"),rs.getString("Stock")});
            }
            jt_productos.setModel(articulos);
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_ag = new javax.swing.JButton();
        jbtn_mo = new javax.swing.JButton();
        jbtn_c = new javax.swing.JButton();
        jSP_1 = new javax.swing.JScrollPane();
        jt_productos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 188, 212));

        jbtn_ag.setText("Agregar");
        jbtn_ag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_agActionPerformed(evt);
            }
        });

        jbtn_mo.setText("Modificar");
        jbtn_mo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_moActionPerformed(evt);
            }
        });

        jbtn_c.setText("Cancelar");
        jbtn_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cActionPerformed(evt);
            }
        });

        jSP_1.setForeground(new java.awt.Color(0, 188, 212));

        jt_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jSP_1.setViewportView(jt_productos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jbtn_ag)
                        .addGap(57, 57, 57)
                        .addComponent(jbtn_mo)
                        .addGap(60, 60, 60)
                        .addComponent(jbtn_c))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jSP_1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_ag)
                    .addComponent(jbtn_mo)
                    .addComponent(jbtn_c))
                .addGap(36, 36, 36)
                .addComponent(jSP_1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtn_cActionPerformed

    private void jbtn_agActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_agActionPerformed
Agregar a = new Agregar();
a.setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_jbtn_agActionPerformed
//que pedo aqui :v
    private void jbtn_moActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_moActionPerformed
        try {
            Modificar mo = new  Modificar();
            mo.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Almacen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtn_moActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Almacen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jSP_1;
    private javax.swing.JButton jbtn_ag;
    private javax.swing.JButton jbtn_c;
    private javax.swing.JButton jbtn_mo;
    private javax.swing.JTable jt_productos;
    // End of variables declaration//GEN-END:variables
}
