/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Abarrotes;

import com.sun.awt.AWTUtilities;
import com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.Timer;
import org.eclipse.persistence.internal.oxm.mappings.Login;

/**
 *
 * @author Olaf G. Cortés
 */
public class loader extends javax.swing.JFrame {
   
    public Timer timer;
    public JFrame loader = this;
    
    /**
     * Creates new form loader
     */
   
    public loader() {
        initComponents();
        AWTUtilities.setWindowOpaque(this,false);
        setLocationRelativeTo(null);
    }
    
    public class Progreso implements ActionListener{
     public void actionPerformed(ActionEvent evt){
        int n = barraProgreso.getValue();
        
        if(n<100){
        n++;
        barraProgreso.setValue(n);
        lblTiempo.setText(Integer.toString(n)+"%");
    }
        else{
            try{
            Thread.sleep(1000);
            }catch(InterruptedException ex){
                Logger.getLogger(Loader.class.getName()).log(Level.SEVERE,null,ex);
            }
            timer.stop();
            Menu men = new Menu();
            men.setVisible(true);
            loader.setVisible(false);
            
        }
    }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTiempo = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        barraProgreso = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTiempo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        getContentPane().add(lblTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 170, 30));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Abarrotes/shop-icon_34368.png"))); // NOI18N
        logo.setText("jLabel1");
        logo.setMaximumSize(new java.awt.Dimension(250, 250));
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 517, 427));
        getContentPane().add(barraProgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 440, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       timer =  new Timer(50,new Progreso());
       timer.start();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loader().setVisible(true);
            }
        });
    }
       

     
     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgreso;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}

